[theme]
primaryColor = "#e94560"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

